version: "3"
services:
  web:
    # replace username/repo:tag with your name and image details
    image: 12ohiodn8/python_flask_rp:v2
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - "3000:80"
    networks:
      - webnet
networks:
  webnet:

